name: Docker
on:
  push:
    branches:
      - "**"
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        id: meta
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/hellomicro
          tags: |
            type=semver,pattern={{version}}
      - uses: docker/login-action@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
