name: Docker
on:
  push:
    branches:
      - "**"
    tags:
      - v*
jobs:
  build:
    uses: michaelmass/actions/.github/workflows/build-dockerhub.yml@master
    with:
      name: hellomicro
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
