name: Docker Publish
on:
  workflow_dispatch: {}
  push:
    branches:
      - "master"
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: michaelmass
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: michaelmass/actions/dagger@master
        with:
          source: ci/publish.ts
          infisical-token: ${{ secrets.INFISICAL_TOKEN }}
          infisical-workspace-id: ${{ secrets.INFISICAL_WORKSPACE_ID }}
